<?php

/**
 * Custom Post Types Configuration
 *
 * This configuration file defines settings for custom post types used within the WordPress theme.
 * Each entry in the array represents a custom post type, with various options as defined by the
 * WordPress function `register_post_type`.
 *
 * If 'labels' are not provided, they will be auto-generated by pluralizing this name.
 *
 * Configuration Options:
 * - 'label': (string) A human-readable name for the post type, defaults to post type's name if not set.
 * - 'labels': (array) An array of labels for this post type.
 * - 'description': (string) A short descriptive summary of the post type.
 * - 'public': (boolean) Whether a post type is intended for use publicly either via the admin interface or by front-end users.
 * - 'exclude_from_search': (boolean) Whether to exclude posts with this post type from front end search results.
 * - 'publicly_queryable': (boolean) Whether queries can be performed on the front end as part of parse_request().
 * - 'show_ui': (boolean) Whether to generate a default UI for managing this post type in the admin.
 * - 'show_in_nav_menus': (boolean) Whether post_type is available for selection in navigation menus.
 * - 'show_in_menu': (boolean) Where to show the post type in the admin menu.
 * - 'menu_position': (integer) The position in the menu order the post type should appear.
 * - 'menu_icon': (string) The url to the icon to be used for this menu or the name of the icon from the iconfont.
 * - 'capability_type': (string|array) The string to use to build the read, edit, and delete capabilities.
 * - 'capabilities': (array) Array of capabilities for this post type.
 * - 'map_meta_cap': (boolean) Whether to use the internal default meta capability handling.
 * - 'hierarchical': (boolean) Whether the post type is hierarchical (e.g. page).
 * - 'supports': (array) An alias for calling add_post_type_support() directly.
 * - 'register_meta_box_cb': (callback) Provide a callback function that sets up the meta boxes for the edit form.
 * - 'taxonomies': (array) An array of taxonomy identifiers that will be registered for the post type.
 * - 'has_archive': (boolean) Whether there should be post type archives.
 * - 'rewrite': (array|bool) Triggers the handling of rewrites for this post type.
 * - 'permalink_epmask': (string) The default rewrite endpoint bitmask.
 * - 'query_var': (boolean|string) Sets the query_var key for this post type.
 * - 'can_export': (boolean) Can this post_type be exported.
 * - 'delete_with_user': (boolean) Whether to delete posts of this type when deleting a user.
 * - 'show_in_rest': (boolean) Whether to expose this post type in the REST API.
 * - 'rest_base': (string) To change the base url of REST API route.
 * - 'rest_controller_class': (class) The controller for handling the REST API requests.
 *
 * Example configuration array:
 * return [
 *     'my_custom_post_type' => [
 *         'label' => 'My Custom Post Type',
 *         'description' => 'A custom post type for special content.',
 *         'public' => true,
 *         'menu_icon' => 'dashicons-admin-customizer',
 *         'supports' => ['title', 'editor', 'thumbnail'],
 *         'show_in_rest' => true,
 *         ... other options ...
 *     ],
 *     ... additional custom post types ...
 * ];
 *
 * Note: Refer to the WordPress codex for more detailed information on each option.
 * @see https://developer.wordpress.org/reference/functions/register_post_type/
 *
 * @var array
 */

return [];
