<?php

/**
<?php

/**
 * Custom Taxonomies Configuration
 *
 * This configuration file defines settings for custom taxonomies used within the WordPress theme.
 * Each entry in the array represents a custom taxonomy, with various options as defined by the
 * WordPress function `register_taxonomy`.
 *
 * If 'labels' are not provided, they will be auto-generated by pluralizing this name.
  *
 * Configuration Options:
 * - 'label': (string) A human-readable name for the taxonomy, defaults to taxonomy's name if not set.
 * - 'labels': (array) An array of labels for this taxonomy.
 * - 'public': (boolean) Whether the taxonomy is intended to be used publicly.
 * - 'publicly_queryable': (boolean) Whether the taxonomy's terms are queryable on the front end.
 * - 'show_ui': (boolean) Whether to generate a default UI for managing this taxonomy in the admin.
 * - 'show_in_menu': (boolean) Whether to show the taxonomy in the admin menu.
 * - 'show_in_nav_menus': (boolean) Whether the taxonomy is available for selection in navigation menus.
 * - 'show_in_rest': (boolean) Whether to include the taxonomy in the REST API.
 * - 'rest_base': (string) The base slug that this taxonomy will use when accessed using the REST API.
 * - 'rest_controller_class': (class) The controller for handling REST API requests.
 * - 'show_tagcloud': (boolean) Whether to allow the Tag Cloud widget to use this taxonomy.
 * - 'show_in_quick_edit': (boolean) Whether to show the taxonomy in the quick/bulk edit panel.
 * - 'meta_box_cb': (callback) Function that will be called to output the taxonomy meta box.
 * - 'show_admin_column': (boolean) Whether to display a column for the taxonomy on its associated post types.
 * - 'description': (string) A short descriptive summary of the taxonomy.
 * - 'hierarchical': (boolean) Whether the taxonomy is hierarchical (like categories).
 * - 'update_count_callback': (callback) Function to call when updating the count of an associated term.
 * - 'query_var': (boolean|string) Sets the query_var key for this taxonomy.
 * - 'rewrite': (array|boolean) Triggers the handling of rewrites for this taxonomy.
 * - 'capabilities': (array) Array of capabilities for this taxonomy.
 * - 'sort': (boolean) Whether this taxonomy should remember the order in which terms are added to objects.
 *
 * Example configuration array:
 * return [
 *     'my_custom_taxonomy' => [
 *         'label' => 'My Custom Taxonomy',
 *         'description' => 'A custom taxonomy for special content.',
 *         'public' => true,
 *         'hierarchical' => true,
 *         'show_in_rest' => true,
 *         ... other options ...
 *     ],
 *     ... additional custom taxonomies ...
 * ];
 *
 * Note: Refer to the WordPress Codex for more detailed information on each option.
 * @see https://developer.wordpress.org/reference/functions/register_taxonomy/
 *
 * @var array
 */
return [];
